"""
Django settings for digimanproject project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ
import dj_database_url
import ssl
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Load environment variables from .env file
env = environ.Env(
    DEBUG=(bool, False)
)
environ.Env.read_env(os.path.join(BASE_DIR, 'backend.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG", default=False)

# Set allowed hosts
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])

# Set security & proxy settings
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=[])
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
CSRF_TRUSTED_ORIGINS = [
    f"https://{host}" for host in env.list("ALLOWED_HOSTS", default=[])
    if not host.startswith("localhost")
]



# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'api',
    'rest_framework_simplejwt',
    'dj_database_url',
    "django_filters",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'digimanproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'digimanproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': env('DB_NAME'),
#         'USER': env('DB_USER'),
#         'PASSWORD': env('DB_PASSWORD'),
#         'HOST': env('DB_HOST'),
#         'PORT': env('DB_PORT'),
#         'OPTIONS': {
#             'sslmode': 'require' if env.bool('DB_SSL_REQUIRE', default=True) else 'prefer',
#         },
#     }
# }
DATABASES = {
    "default": dj_database_url.config(
        default=env("DB_URL", default=""),
        conn_max_age=600,
        ssl_require=True,
    )
}

AUTH_USER_MODEL = 'api.User'


# REST Framework

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Collect static files from all apps into this directory (for production)
STATIC_ROOT = BASE_DIR / 'collected_static'

# Additional directories to look for static files
# STATICFILES_DIRS = [
#     BASE_DIR / "static",  # Global static files
# ]


# WhiteNoise for static file serving

MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# Celery Settings

CELERY_BROKER_URL = env("REDIS_URL")
CELERY_RESULT_BACKEND = env("REDIS_URL")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"


# Celery Wakeup

IS_RENDER = env.bool("IS_RENDER", False)
CELERY_WAKE_URL = env("CELERY_WAKE_URL", default="")


# Django Redis Settings

DJANGO_REDIS_URL = env("DJANGO_REDIS_URL")

parsed = urlparse(DJANGO_REDIS_URL)
USE_SSL = parsed.scheme == "rediss"

CACHE_OPTIONS = {
    "CLIENT_CLASS": "django_redis.client.DefaultClient",
}

if USE_SSL:
    CACHE_OPTIONS["CONNECTION_POOL_KWARGS"] = {
        "ssl_cert_reqs": ssl.CERT_NONE,
    }

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": DJANGO_REDIS_URL,
        "OPTIONS": CACHE_OPTIONS,
    }
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Jazzmin Settings For Styling Admin UI

JAZZMIN_SETTINGS = {
    # --- Basic UI branding (optional) ---
    "site_title": "Digiman Admin",
    "site_header": "Digiman Administration",
    "welcome_sign": "Welcome to Digiman Admin",
    "copyright": "© 2025 Digiman",
    
    # --- Sidebar configuration ---
    "show_sidebar": True,
    "navigation_expanded": False,

    # --- custom group title --- 
    "menus": [
        {
            "app": "api",
            "label": "User Accounts",
            "models": [
                "api.User",
                "api.Reader",
                "api.Administrator",
            ],
        },
        {
            "app": "api",
            "label": "Manga Content",
            "models": [
                "api.MangaTitle",
                "api.Author",
                "api.Genre",
                "api.Chapter",
                "api.Comment",
            ],
        },
        {
            "app": "api",
            "label": "System Management",
            "models": [
                "api.LogEntry",
                "api.FlaggedContent",
            ],
        },
    ],

    # --- Optional visuals ---
    "icons": {
        "api.User": "fas fa-user",
        "api.Reader": "fas fa-book-reader",
        "api.Administrator": "fas fa-user-shield",
        "api.MangaTitle": "fas fa-book",
        "api.Author": "fas fa-user-tie",
        "api.Genre": "fas fa-list",
        "api.Chapter": "fas fa-scroll",
        "api.Page": "fas fa-image",
        "api.Comment": "fas fa-comments",
        "api.LogEntry": "fas fa-history",
        "api.FlaggedContent": "fas fa-flag",
    },
}

