# Generated by Django 5.2.7 on 2025-11-06 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_administrator_options_alter_reader_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='avatar',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
