# Generated by Django 5.2.7 on 2025-11-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_page_unique_page_per_chapter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangatitle',
            name='alternative_title',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('chapter', 'page_number'), name='unique_page_per_chapter'),
        ),
    ]
