# Generated by Django 5.2.7 on 2025-11-20 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_mangatitle_alternative_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_image',
        ),
        migrations.AddField(
            model_name='comment',
            name='attached_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='flaggedcontent',
            name='details',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('scheduled', 'Scheduled'), ('expired', 'Expired'), ('hidden', 'Hidden')], default='active'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted'), ('hidden', 'Hidden')], default='active'),
        ),
        migrations.AlterField(
            model_name='flaggedcontent',
            name='target_content_type',
            field=models.CharField(choices=[('mangatitle', 'MangaTitle'), ('chapter', 'Chapter'), ('page', 'Page'), ('comment', 'Comment'), ('user', 'User')]),
        ),
        migrations.AlterField(
            model_name='librarylist',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('built-in', 'Built-in')], default='private'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='action_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')]),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='target_object_type',
            field=models.CharField(choices=[('manga_title', 'MangaTitle'), ('chapter', 'Chapter'), ('page', 'Page'), ('genre', 'Genre'), ('author', 'Author'), ('comment', 'Comment'), ('user', 'User'), ('report', 'Report'), ('flagged_content', 'FlaggedContent'), ('announcement', 'Announcement'), ('penalty', 'Penalty')]),
        ),
        migrations.AlterField(
            model_name='mangatitle',
            name='alternative_title',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mangatitle',
            name='preview_chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.chapter'),
        ),
        migrations.AlterField(
            model_name='mangatitle',
            name='publication_status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('finished', 'Finished'), ('dropped', 'Dropped')], default='ongoing'),
        ),
        migrations.AlterField(
            model_name='mangatitle',
            name='title',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_object_type',
            field=models.CharField(choices=[('manga_title', 'MangaTitle'), ('chapter', 'Chapter'), ('comment', 'Comment'), ('report', 'Report'), ('announcement', 'Announcement')]),
        ),
        migrations.AlterField(
            model_name='readerpreferences',
            name='image_size_mode',
            field=models.CharField(choices=[('fit_width', 'Fit Width'), ('fit_height', 'Fit Height'), ('fit_both', 'Fit Both')], default='fit_both'),
        ),
        migrations.AlterField(
            model_name='readerpreferences',
            name='page_display_style',
            field=models.CharField(choices=[('single-page', 'Single-Page'), ('double-page', 'Double-Page'), ('long_strip', 'Long Strip'), ('wide_strip', 'Wide Strip')], default='single-page'),
        ),
        migrations.AlterField(
            model_name='readerpreferences',
            name='reading_direction',
            field=models.CharField(choices=[('left_to_right', 'Left to Right'), ('right_to_left', 'Right to Left')], default='left_to_right'),
        ),
        migrations.AlterField(
            model_name='readerpreferences',
            name='theme_mode',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('reader', 'Reader')], default='reader'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('deactivated', 'Deactivated')], default='active'),
        ),
        migrations.DeleteModel(
            name='OfflineChapter',
        ),
    ]
