# Generated by Django 5.2.7 on 2025-11-20 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_comment_content_remove_comment_is_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='attached_image',
            new_name='attached_image_url',
        ),
    ]
