# Generated by Django 5.2.7 on 2025-11-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_attached_image_comment_attached_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='flaggedcontent',
            name='content_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='flaggedcontent',
            name='dominant_attribute',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='action_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('autoresolveflag', 'AutoResolveFlag'), ('resolveflag', 'ResolveFlag')]),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='target_object_type',
            field=models.CharField(choices=[('mangatitle', 'MangaTitle'), ('chapter', 'Chapter'), ('page', 'Page'), ('genre', 'Genre'), ('author', 'Author'), ('comment', 'Comment'), ('user', 'User'), ('report', 'Report'), ('flaggedcontent', 'FlaggedContent'), ('announcement', 'Announcement'), ('penalty', 'Penalty')]),
        ),
    ]
