# Generated by Django 5.2.7 on 2025-11-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_flaggedcontent_content_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flaggedcontent',
            old_name='target_content_id',
            new_name='target_object_id',
        ),
        migrations.RenameField(
            model_name='flaggedcontent',
            old_name='target_content_type',
            new_name='target_object_type',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
