# Generated by Django 5.2.7 on 2025-11-28 04:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_target_content_id_flaggedcontent_target_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('deactivated', 'Deactivated'), ('deleted', 'Deleted')], default='active'),
        ),
        migrations.CreateModel(
            name='MangaReaderStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_reader_visited', models.BooleanField(default=False)),
                ('is_reader_read', models.BooleanField(default=False)),
                ('is_reader_followed', models.BooleanField(default=False)),
                ('is_reader_commented', models.BooleanField(default=False)),
                ('manga_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manga_reader_statistics', to='api.mangatitle')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manga_reader_statistics', to='api.reader')),
            ],
        ),
    ]
