# Generated by Django 5.2.7 on 2025-12-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_user_status_mangareaderstatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flaggedcontent',
            name='target_object_type',
            field=models.CharField(choices=[('mangatitle', 'MangaTitle'), ('chapter', 'Chapter'), ('page', 'Page'), ('comment', 'Comment'), ('user', 'User'), ('reader', 'Reader'), ('administrator', 'Administrator')]),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='target_object_type',
            field=models.CharField(choices=[('mangatitle', 'MangaTitle'), ('chapter', 'Chapter'), ('page', 'Page'), ('genre', 'Genre'), ('author', 'Author'), ('comment', 'Comment'), ('user', 'User'), ('reader', 'Reader'), ('administrator', 'Administrator'), ('report', 'Report'), ('flaggedcontent', 'FlaggedContent'), ('announcement', 'Announcement'), ('penalty', 'Penalty')]),
        ),
    ]
