# Generated by Django 5.2.7 on 2026-04-08 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_flaggedcontent_target_object_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='readerpreferences',
            name='reader',
        ),
        migrations.RemoveField(
            model_name='mangareaderstatistics',
            name='is_reader_followed',
        ),
        migrations.RemoveField(
            model_name='mangatitle',
            name='preview_chapter',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='age',
        ),
        migrations.RemoveField(
            model_name='report',
            name='admin_message',
        ),
        migrations.AddField(
            model_name='mangareaderstatistics',
            name='star_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mangatitle',
            name='first_free_chapter_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mangatitle',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mangatitle',
            name='last_free_chapter_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='target_object_type',
            field=models.CharField(choices=[('mangatitle', 'MangaTitle'), ('chapter', 'Chapter'), ('page', 'Page'), ('genre', 'Genre'), ('author', 'Author'), ('comment', 'Comment'), ('user', 'User'), ('reader', 'Reader'), ('administrator', 'Administrator'), ('report', 'Report'), ('flaggedcontent', 'FlaggedContent'), ('penalty', 'Penalty')]),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LibraryList',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='ReaderPreferences',
        ),
    ]
