# Generated by Django 5.2.7 on 2026-04-13 16:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_delete_announcement_remove_notification_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Free', max_length=100, unique=True)),
                ('frequency', models.CharField(choices=[('permanent', 'Permanent'), ('hourly', 'Hourly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='permanent', max_length=100)),
                ('price_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.JSONField(default=list)),
                ('features', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('provider', models.CharField(choices=[('Stripe', 'Stripe'), ('Momo', 'Momo'), ('None', 'None')], default='Stripe', max_length=100)),
                ('external_price_id', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='penalty',
            old_name='duration_days',
            new_name='duration_hours',
        ),
        migrations.CreateModel(
            name='ReaderSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('last_billing_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('past_due', 'Past Due')], default='active', max_length=100)),
                ('is_auto_renewal', models.BooleanField(default=True)),
                ('provider', models.CharField(choices=[('Stripe', 'Stripe'), ('Momo', 'Momo'), ('None', 'None')], default='None', max_length=100)),
                ('external_subscription_id', models.CharField(default='', max_length=100)),
                ('reader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reader_subscription', to='api.reader')),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reader_subscription', to='api.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('auto_renewal', 'Auto Renewal')], default='purchase', max_length=100)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(choices=[('Stripe', 'Stripe'), ('Momo', 'Momo'), ('None', 'None')], default='Stripe', max_length=100)),
                ('external_transaction_id', models.CharField(default='', max_length=100)),
                ('reader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='api.reader')),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='api.subscriptionplan')),
            ],
        ),
    ]
