# Generated by Django 5.2.7 on 2026-04-16 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_subscriptionplan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='external_price_id',
            new_name='stripe_price_id',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='provider',
        ),
    ]
