# Generated by Django 5.2.7 on 2026-04-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_external_price_id_subscriptionplan_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='stripe_price_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
