# Generated by Django 5.2.7 on 2026-04-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_subscriptionplan_stripe_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='external_customer_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='readersubscription',
            name='external_customer_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('momo', 'Momo'), ('none', 'None')], default='stripe', max_length=100),
        ),
        migrations.AlterField(
            model_name='readersubscription',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('momo', 'Momo'), ('none', 'None')], default='none', max_length=100),
        ),
    ]
