# Generated by Django 5.2.7 on 2026-04-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_paymenttransaction_external_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='flaggedcontent',
            options={'ordering': ['-flagged_at'], 'verbose_name': 'Flagged Content', 'verbose_name_plural': 'Flagged Contents'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='logentry',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Log Entry', 'verbose_name_plural': 'Log Entries'},
        ),
        migrations.AlterModelOptions(
            name='mangareaderstatistics',
            options={'verbose_name': 'Manga Reader Statistics', 'verbose_name_plural': 'Manga Reader Statistics'},
        ),
        migrations.AlterModelOptions(
            name='mangatitle',
            options={'verbose_name': 'Manga Title', 'verbose_name_plural': 'Manga Titles'},
        ),
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment Transaction', 'verbose_name_plural': 'Payment Transactions'},
        ),
        migrations.AlterModelOptions(
            name='penalty',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Penalty', 'verbose_name_plural': 'Penalties'},
        ),
        migrations.AlterModelOptions(
            name='readersubscription',
            options={'verbose_name': 'Reader Subscription', 'verbose_name_plural': 'Reader Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='readingprogress',
            options={'verbose_name': 'Reading Progress', 'verbose_name_plural': 'Reading Progresses'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['price_usd'], 'verbose_name': 'Subscription Plan', 'verbose_name_plural': 'Subscription Plans'},
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='provider',
            field=models.CharField(choices=[('Stripe', 'Stripe'), ('Momo', 'Momo'), ('None', 'None')], default='Stripe', max_length=100),
        ),
        migrations.AlterField(
            model_name='readersubscription',
            name='provider',
            field=models.CharField(choices=[('Stripe', 'Stripe'), ('Momo', 'Momo'), ('None', 'None')], default='None', max_length=100),
        ),
    ]
