# Generated by Django 5.2.7 on 2026-05-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_author_options_alter_flaggedcontent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readersubscription',
            name='last_payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('unpaid', 'Unpaid'), ('failed', 'Failed'), ('none', 'None')], default='none', max_length=100),
        ),
    ]
