# Generated by Django 5.2.7 on 2026-05-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_readersubscription_last_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readersubscription',
            name='last_payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('failed', 'Failed'), ('none', 'None')], default='none', max_length=100),
        ),
    ]
