# Generated by Django 5.2.7 on 2026-05-15 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_readersubscription_last_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readersubscription',
            name='last_billing_date',
        ),
        migrations.RemoveField(
            model_name='readersubscription',
            name='last_payment_status',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='failed_reason',
            field=models.TextField(choices=[('card_declined', 'Card Declined'), ('insufficient_funds', 'Insufficient Funds'), ('other', 'Other'), ('none', 'None')], default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='readersubscription',
            name='last_payment_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reader_subscription', to='api.paymenttransaction'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('failed', 'Failed')], default='paid', max_length=100),
        ),
    ]
