# Generated by Django 5.2.7 on 2026-05-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_readersubscription_last_billing_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readersubscription',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readersubscription',
            name='last_purchase_status',
            field=models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('failed', 'Failed')], default='success', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='failed_reason',
            field=models.TextField(choices=[('card_declined', 'Card Declined'), ('insufficient_funds', 'Insufficient Funds'), ('processing_error', 'Processing Error'), ('generic_decline', 'Generic Decline'), ('server_error', 'Server Error'), ('other', 'Other'), ('none', 'None')], default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='readersubscription',
            name='is_auto_renewal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='readersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('past_due', 'Past Due'), ('ended', 'Ended')], default='active', max_length=100),
        ),
    ]
