# Generated by Django 5.2.7 on 2026-05-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_readersubscription_ended_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readersubscription',
            name='last_purchase_status',
            field=models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('failed', 'Failed'), ('none', 'None')], default='none', max_length=100),
        ),
    ]
