# Generated by Django 5.2.7 on 2026-05-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_readersubscription_last_purchase_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='failed_reason',
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
