# Generated by Django 5.2.7 on 2026-05-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_paymenttransaction_failed_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='next_payment_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
