# Generated by Django 5.2.7 on 2026-05-28 04:22

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_paymenttransaction_next_payment_attempt_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationThreshold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=10)),
                ('attribute', models.CharField(max_length=100)),
                ('flag_threshold', models.FloatField(default=0.0)),
                ('ban_threshold', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('service_api', models.CharField(choices=[('perspective_api', 'Perspective API'), ('sightengine', 'Sightengine')], default='perspective_api', max_length=20)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Moderation Threshold',
                'verbose_name_plural': 'Moderation Thresholds',
            },
        ),
    ]
