# Generated by Django 5.2.7 on 2026-05-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_moderationthreshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationthreshold',
            name='service_api',
            field=models.CharField(choices=[('perspective_api', 'Perspective API'), ('sightengine', 'Sightengine')], default='perspective_api', max_length=50),
        ),
    ]
