# Generated by Django 5.2.7 on 2026-05-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_moderationthreshold_service_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationthreshold',
            name='ban_threshold',
            field=models.FloatField(default=1.0),
        ),
    ]
