# Generated by Django 5.2.7 on 2026-06-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_moderationthreshold_ban_threshold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='is_moderated',
        ),
        migrations.AddField(
            model_name='comment',
            name='last_moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('safe', 'Safe'), ('flagged', 'Flagged'), ('banned', 'Banned'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='logentry',
            name='last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('safe', 'Safe'), ('flagged', 'Flagged'), ('banned', 'Banned'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='logentry',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('safe', 'Safe'), ('flagged', 'Flagged'), ('banned', 'Banned'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='flaggedcontent',
            name='target_object_type',
            field=models.CharField(choices=[('comment', 'Comment'), ('user', 'User'), ('reader', 'Reader'), ('administrator', 'Administrator')]),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='target_object_type',
            field=models.CharField(choices=[('mangatitle', 'MangaTitle'), ('chapter', 'Chapter'), ('page', 'Page'), ('genre', 'Genre'), ('author', 'Author'), ('comment', 'Comment'), ('user', 'User'), ('reader', 'Reader'), ('administrator', 'Administrator'), ('report', 'Report'), ('flaggedcontent', 'FlaggedContent'), ('penalty', 'Penalty'), ('moderationthreshold', 'ModerationThreshold')]),
        ),
    ]
