# Generated by Django 5.2.7 on 2026-06-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_comment_options_remove_logentry_is_moderated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flaggedcontent',
            name='moderation_status',
            field=models.CharField(choices=[('flagged', 'Flagged'), ('banned', 'Banned')], default='flagged', max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted'), ('hidden', 'Hidden')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='mangatitle',
            name='publication_status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('finished', 'Finished'), ('dropped', 'Dropped')], default='ongoing', max_length=20),
        ),
    ]
