# Generated by Django 5.2.7 on 2026-06-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_flaggedcontent_moderation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('safe', 'Safe'), ('flagged', 'Flagged'), ('banned', 'Banned'), ('failed', 'Failed')], default='safe', max_length=20),
        ),
    ]
