# Generated by Django 5.2.7 on 2026-06-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_comment_moderation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('safe', 'Safe'), ('flagged', 'Flagged'), ('banned', 'Banned'), ('failed', 'Failed')], default='safe', max_length=20),
        ),
    ]
