# Generated by Django 5.2.7 on 2026-06-03 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_user_moderation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flaggedcontent',
            old_name='moderation_status',
            new_name='flag_status',
        ),
    ]
