# Generated by Django 5.2.7 on 2026-06-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_rename_moderation_status_flaggedcontent_flag_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='moderation_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='moderation_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
