# Generated by Django 5.2.7 on 2026-06-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_logentry_moderation_finished_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('safe', 'Safe'), ('flagged', 'Flagged'), ('banned', 'Banned'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('safe', 'Safe'), ('flagged', 'Flagged'), ('banned', 'Banned'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
