# Generated by Django 5.2.7 on 2026-06-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_comment_moderation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='action_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('autoresolveflag', 'Auto Resolve Flag'), ('resolveflag', 'Resolve Flag'), ('purchase', 'Subscription Purchase'), ('autorenewal', 'Subscription Auto Renewal'), ('renewaltoggle', 'Subscription Renewal Toggle'), ('ended', 'Subscription ended')]),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='target_object_type',
            field=models.CharField(choices=[('mangatitle', 'MangaTitle'), ('chapter', 'Chapter'), ('page', 'Page'), ('genre', 'Genre'), ('author', 'Author'), ('comment', 'Comment'), ('user', 'User'), ('reader', 'Reader'), ('administrator', 'Administrator'), ('report', 'Report'), ('flaggedcontent', 'FlaggedContent'), ('penalty', 'Penalty'), ('moderationthreshold', 'ModerationThreshold'), ('subscriptionplan', 'SubscriptionPlan'), ('readersubscription', 'ReaderSubscription')]),
        ),
    ]
